/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashxRouteImport } from './routes/dashx'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as UsernameSlugRouteImport } from './routes/$username.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardPageRouteImport } from './routes/dashboard/page'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashxIndexRouteImport } from './routes/dashx/index'
import { Route as DashxMailRouteImport } from './routes/dashx/mail'
import { Route as DashxOrdersRouteImport } from './routes/dashx/orders'
import { Route as DashxPaymentsRouteImport } from './routes/dashx/payments'
import { Route as DashxShopsRouteImport } from './routes/dashx/shops'
import { Route as DashxStorageRouteImport } from './routes/dashx/storage'
import { Route as DashxUsersRouteImport } from './routes/dashx/users'
import { Route as PayReturnRouteImport } from './routes/pay/return'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as DashboardProductsIdRouteImport } from './routes/dashboard/products.$id'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products.new'
import { Route as PayDemoOrderRefRouteImport } from './routes/pay/demo.$orderRef'
import { Route as PaySuccessOrderRefRouteImport } from './routes/pay/success.$orderRef'
import { Route as ApiFilesDTokenRouteImport } from './routes/api/files/d.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashxRoute = DashxRouteImport.update({
  id: '/dashx',
  path: '/dashx',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRoute,
} as any)
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UsernameRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPageRoute = DashboardPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashxIndexRoute = DashxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashxRoute,
} as any)
const DashxMailRoute = DashxMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => DashxRoute,
} as any)
const DashxOrdersRoute = DashxOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashxRoute,
} as any)
const DashxPaymentsRoute = DashxPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashxRoute,
} as any)
const DashxShopsRoute = DashxShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => DashxRoute,
} as any)
const DashxStorageRoute = DashxStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashxRoute,
} as any)
const DashxUsersRoute = DashxUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashxRoute,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIdRoute = DashboardProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const PayDemoOrderRefRoute = PayDemoOrderRefRouteImport.update({
  id: '/pay/demo/$orderRef',
  path: '/pay/demo/$orderRef',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySuccessOrderRefRoute = PaySuccessOrderRefRouteImport.update({
  id: '/pay/success/$orderRef',
  path: '/pay/success/$orderRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDTokenRoute = ApiFilesDTokenRouteImport.update({
  id: '/api/files/d/$token',
  path: '/api/files/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashx': typeof DashxRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/page': typeof DashboardPageRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashx/mail': typeof DashxMailRoute
  '/dashx/orders': typeof DashxOrdersRoute
  '/dashx/payments': typeof DashxPaymentsRoute
  '/dashx/shops': typeof DashxShopsRoute
  '/dashx/storage': typeof DashxStorageRoute
  '/dashx/users': typeof DashxUsersRoute
  '/pay/return': typeof PayReturnRoute
  '/$username/': typeof UsernameIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashx/': typeof DashxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/pay/demo/$orderRef': typeof PayDemoOrderRefRoute
  '/pay/success/$orderRef': typeof PaySuccessOrderRefRoute
  '/api/files/d/$token': typeof ApiFilesDTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/page': typeof DashboardPageRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashx/mail': typeof DashxMailRoute
  '/dashx/orders': typeof DashxOrdersRoute
  '/dashx/payments': typeof DashxPaymentsRoute
  '/dashx/shops': typeof DashxShopsRoute
  '/dashx/storage': typeof DashxStorageRoute
  '/dashx/users': typeof DashxUsersRoute
  '/pay/return': typeof PayReturnRoute
  '/$username': typeof UsernameIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashx': typeof DashxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/pay/demo/$orderRef': typeof PayDemoOrderRefRoute
  '/pay/success/$orderRef': typeof PaySuccessOrderRefRoute
  '/api/files/d/$token': typeof ApiFilesDTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashx': typeof DashxRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/page': typeof DashboardPageRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashx/mail': typeof DashxMailRoute
  '/dashx/orders': typeof DashxOrdersRoute
  '/dashx/payments': typeof DashxPaymentsRoute
  '/dashx/shops': typeof DashxShopsRoute
  '/dashx/storage': typeof DashxStorageRoute
  '/dashx/users': typeof DashxUsersRoute
  '/pay/return': typeof PayReturnRoute
  '/$username/': typeof UsernameIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashx/': typeof DashxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/pay/demo/$orderRef': typeof PayDemoOrderRefRoute
  '/pay/success/$orderRef': typeof PaySuccessOrderRefRoute
  '/api/files/d/$token': typeof ApiFilesDTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/dashboard'
    | '/dashx'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/$username/$slug'
    | '/dashboard/orders'
    | '/dashboard/page'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashx/mail'
    | '/dashx/orders'
    | '/dashx/payments'
    | '/dashx/shops'
    | '/dashx/storage'
    | '/dashx/users'
    | '/pay/return'
    | '/$username/'
    | '/dashboard/'
    | '/dashx/'
    | '/api/auth/$'
    | '/api/files/upload'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/pay/demo/$orderRef'
    | '/pay/success/$orderRef'
    | '/api/files/d/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/$username/$slug'
    | '/dashboard/orders'
    | '/dashboard/page'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashx/mail'
    | '/dashx/orders'
    | '/dashx/payments'
    | '/dashx/shops'
    | '/dashx/storage'
    | '/dashx/users'
    | '/pay/return'
    | '/$username'
    | '/dashboard'
    | '/dashx'
    | '/api/auth/$'
    | '/api/files/upload'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/pay/demo/$orderRef'
    | '/pay/success/$orderRef'
    | '/api/files/d/$token'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/dashboard'
    | '/dashx'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/$username/$slug'
    | '/dashboard/orders'
    | '/dashboard/page'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashx/mail'
    | '/dashx/orders'
    | '/dashx/payments'
    | '/dashx/shops'
    | '/dashx/storage'
    | '/dashx/users'
    | '/pay/return'
    | '/$username/'
    | '/dashboard/'
    | '/dashx/'
    | '/api/auth/$'
    | '/api/files/upload'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/pay/demo/$orderRef'
    | '/pay/success/$orderRef'
    | '/api/files/d/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DashxRoute: typeof DashxRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PayReturnRoute: typeof PayReturnRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  PayDemoOrderRefRoute: typeof PayDemoOrderRefRoute
  PaySuccessOrderRefRoute: typeof PaySuccessOrderRefRoute
  ApiFilesDTokenRoute: typeof ApiFilesDTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashx': {
      id: '/dashx'
      path: '/dashx'
      fullPath: '/dashx'
      preLoaderRoute: typeof DashxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof UsernameSlugRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/page': {
      id: '/dashboard/page'
      path: '/page'
      fullPath: '/dashboard/page'
      preLoaderRoute: typeof DashboardPageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashx/': {
      id: '/dashx/'
      path: '/'
      fullPath: '/dashx/'
      preLoaderRoute: typeof DashxIndexRouteImport
      parentRoute: typeof DashxRoute
    }
    '/dashx/mail': {
      id: '/dashx/mail'
      path: '/mail'
      fullPath: '/dashx/mail'
      preLoaderRoute: typeof DashxMailRouteImport
      parentRoute: typeof DashxRoute
    }
    '/dashx/orders': {
      id: '/dashx/orders'
      path: '/orders'
      fullPath: '/dashx/orders'
      preLoaderRoute: typeof DashxOrdersRouteImport
      parentRoute: typeof DashxRoute
    }
    '/dashx/payments': {
      id: '/dashx/payments'
      path: '/payments'
      fullPath: '/dashx/payments'
      preLoaderRoute: typeof DashxPaymentsRouteImport
      parentRoute: typeof DashxRoute
    }
    '/dashx/shops': {
      id: '/dashx/shops'
      path: '/shops'
      fullPath: '/dashx/shops'
      preLoaderRoute: typeof DashxShopsRouteImport
      parentRoute: typeof DashxRoute
    }
    '/dashx/storage': {
      id: '/dashx/storage'
      path: '/storage'
      fullPath: '/dashx/storage'
      preLoaderRoute: typeof DashxStorageRouteImport
      parentRoute: typeof DashxRoute
    }
    '/dashx/users': {
      id: '/dashx/users'
      path: '/users'
      fullPath: '/dashx/users'
      preLoaderRoute: typeof DashxUsersRouteImport
      parentRoute: typeof DashxRoute
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/$id': {
      id: '/dashboard/products/$id'
      path: '/$id'
      fullPath: '/dashboard/products/$id'
      preLoaderRoute: typeof DashboardProductsIdRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/pay/demo/$orderRef': {
      id: '/pay/demo/$orderRef'
      path: '/pay/demo/$orderRef'
      fullPath: '/pay/demo/$orderRef'
      preLoaderRoute: typeof PayDemoOrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/success/$orderRef': {
      id: '/pay/success/$orderRef'
      path: '/pay/success/$orderRef'
      fullPath: '/pay/success/$orderRef'
      preLoaderRoute: typeof PaySuccessOrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/d/$token': {
      id: '/api/files/d/$token'
      path: '/api/files/d/$token'
      fullPath: '/api/files/d/$token'
      preLoaderRoute: typeof ApiFilesDTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UsernameRouteChildren {
  UsernameSlugRoute: typeof UsernameSlugRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameSlugRoute: UsernameSlugRoute,
  UsernameIndexRoute: UsernameIndexRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

interface DashboardProductsRouteChildren {
  DashboardProductsIdRoute: typeof DashboardProductsIdRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsIdRoute: DashboardProductsIdRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

interface DashboardRouteChildren {
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPageRoute: typeof DashboardPageRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPageRoute: DashboardPageRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DashxRouteChildren {
  DashxMailRoute: typeof DashxMailRoute
  DashxOrdersRoute: typeof DashxOrdersRoute
  DashxPaymentsRoute: typeof DashxPaymentsRoute
  DashxShopsRoute: typeof DashxShopsRoute
  DashxStorageRoute: typeof DashxStorageRoute
  DashxUsersRoute: typeof DashxUsersRoute
  DashxIndexRoute: typeof DashxIndexRoute
}

const DashxRouteChildren: DashxRouteChildren = {
  DashxMailRoute: DashxMailRoute,
  DashxOrdersRoute: DashxOrdersRoute,
  DashxPaymentsRoute: DashxPaymentsRoute,
  DashxShopsRoute: DashxShopsRoute,
  DashxStorageRoute: DashxStorageRoute,
  DashxUsersRoute: DashxUsersRoute,
  DashxIndexRoute: DashxIndexRoute,
}

const DashxRouteWithChildren = DashxRoute._addFileChildren(DashxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DashxRoute: DashxRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PayReturnRoute: PayReturnRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  PayDemoOrderRefRoute: PayDemoOrderRefRoute,
  PaySuccessOrderRefRoute: PaySuccessOrderRefRoute,
  ApiFilesDTokenRoute: ApiFilesDTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
